[package]
name = "k5tool"
version = "0.1.0"
edition = "2021"

authors = ["Aaron Griffith <aargri@gmail.com>"]

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive", "wrap_help"] }
hexdump = "0.1"
indicatif = "0.17"
k5lib = { path = "../k5lib" }
nom = "7"
serialport = "4"
