[package]
name = "k5lib"
version = "0.1.0"
edition = "2021"

authors = ["Aaron Griffith <aargri@gmail.com>"]

[dependencies]
crc = "3"
nom = "7"
void = "1"

[dev-dependencies]
quickcheck = "1"
quickcheck_macros = "1"

[features]
default = ["std"]
alloc = []
std = ["alloc"]
