[package]
name = "k5firmware"
version = "0.1.0"
edition = "2021"

authors = ["Aaron Griffith <aargri@gmail.com>"]

[dependencies]
cortex-m = { version = "0.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7"
critical-section = "1"
dp32g030 = { path = "../dp32g030" }
panic-halt = "0.2"

[profile.release]
codegen-units = 1
debug = true
lto = true
#opt-level = "z"
panic = "abort"
