strict = true
atomics = true
atomics_feature = "atomics"
impl_debug = true
impl_defmt = "defmt"
reexport_core_peripherals = true
reexport_interrupt = true

# I like the all-caps names for most things
ident_formats_theme = "legacy"
[ident_formats.enum_value]
case = "pascal"
