[package]
name = "bk4819"
version = "0.1.0"
edition = "2021"

authors = ["Aaron Griffith <aargri@gmail.com>"]

[dependencies]
bitfield-struct = "0.8"
defmt = { version = "0.3.5", optional = true }
embedded-hal = "1"

[features]
defmt = ["dep:defmt"]
